### ISSUE TITLE
Some weird things

### ISSUE THREAD

**Issue by 002gRTEah3mRYH** [nknorg/nMobile#142] opened 2022-12-20 23:56 UTC
Hello, being open source is good but

Where's 1.4.0?
Why you don't provide a link on your website nMobile?
Why is has 4 trackers?

This looks really suspect

**Comment by jiangzhiguo1992** [comment] 2023-01-28 09:19
1. The code of 1.4.0 is still under review.
2. At present, the official website has the download address of nMobile, and you can download the versions of apk, android, and ios. You can check it out here: https://nmobile.nkn.org.
3. Regarding the tracker issue, I have already responded to it in other issues, you can read it here: #137.

**Comment by jiangzhiguo1992** [comment] 2023-01-28 09:20
1. The code of 1.4.0 is still under review.
2. At present, the official website has the download address of nMobile, and you can download the versions of apk, android, and ios. You can check it out here: https://nmobile.nkn.org.
3. Regarding the tracker issue, I have already responded to it in other issues, you can read it here: #137.

**Comment by abebeos** [comment] 2023-01-29 18:14
@jiangzhiguo1992 , ty for your reply! To clarify, the OP meant "the 1.4.0 source-code", and the website should point to the source-code, even (or especially) the one under development.

@002gRTEah3mRYH , I'd like to apologize for the confusion and frustration.

As an observer (I evaluate NKN for use in personal decades-term projects) I noticed that NKN does not follow all standard-procedures, but this does not mean that it is suspicious.

Usually the answer is: so many work, so little time!

> Where's 1.4.0?

You can find the code right here:

https://github.com/jiangzhiguo1992/nMobile/releases/tag/1.4.0(275)

It is open source, MIT Licensed, whenever in doubt, fork it quickly just to be save (standard-procedure).

> Why you don't provide a link on your website nMobile?

As said, possibly folks is just busy.

> Why is has 4 trackers?

Here I am 100% with you.

I would expect 0 (zero) trackers, no excuses. I wouldn't even want a software with an "opt-in" for this tracking, but would want a version with "0 trackers by design" - even if its more inconvenient.

**Comment by jiangzhiguo1992** [comment] 2023-01-30 02:29
Thank you very much for your suggestion, we did neglect the standard-procedures in the previous time, and invest more time in the future.

We have the GitHub link of the NKN on the official [website,](nkn.org) but there is no unique link for nMobile alone.

Regarding the tracker, there are currently four that do violate the idea of decentralization. Some functions rely heavily on this, such as notification push, but we will explore solutions.

**Comment by abebeos** [comment] 2023-01-31 04:40
> Where's 1.4.0?

@002gRTEah3mRYH , landed:

https://github.com/nknorg/nMobile/releases/tag/v1.4.1(280)

**Comment by jiangzhiguo1992** [comment] 2023-01-31 08:40
here    https://github.com/nknorg/nMobile/releases/tag/v1.4.0(272)

**Closed** 2023-08-07 02:40 UTC
